version: '3'

services:
  tinc:
    image: croc/tinc
    environment:
      SITENAME: "siteA"
      PORT: "655"
      LANIP: "192.168.0.253/24"
      SUBNET: "192.168.0.0/19"
    volumes:
      - './tinc/config:/etc/tinc/site2site/hosts'
      - '/etc/localtime:/etc/localtime:ro'
    privileged: true
    network_mode: "host"
    restart: always
  sync:
    image: resilio/sync
    depends_on:
      - tinc
    volumes:
       - './sync/config:/mnt/sync/config'
       - './tinc/config:/mnt/sync/folders/config'
       - '/etc/localtime:/etc/localtime:ro'
    ports:
       - '8888:8888'
       - '55555:55555'
    restart: always
